name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"

    - name: Build with Gradle
      env: 
        TMDB_V3_API_TOKEN: ${{ secrets.TMDB_V3_API_TOKEN }}
        TMDB_V4_API_TOKEN: ${{ secrets.TMDB_V4_API_TOKEN }}
      run: |
          chmod +x ./gradlew 
          ./gradlew assembleRelease --stacktrace
          
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: PopMovies
        path: app/build/outputs/apk/release/app-release-unsigned.apk
